name: The SleepyTown Collection
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85856
title: 'A new multi-media children property being developed for a mobile, global children generation.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe98e7'
    - '#e2dddf'
    - '#9f7998'
    - '#1d1d20'
    - '#abcf44'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
