name: The SleepyTown Collection
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85856
title: 'A new multi-media children property being developed for a mobile, global children generation.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3fb34f'
    - '#183b1d'
    - '#eac62c'
    - '#00ff00'
    - '#e66f31'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
