name: The SleepyTown Collection
favicon: null
layout_spectrum: 0.99321
typography_spectrum: 0.71464
title: 'A new multi-media children property being developed for a mobile, global children generation.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21a19c'
    - '#1d1d1f'
    - '#696371'
    - '#fef7d6'
    - '#e6212d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
